### ISSUE TITLE
Brave browser github link is wrong.

### ISSUE THREAD

**Issue by ghost** [srevinsaju/Brave-AppImage#5]
The GitHub link of brave browser you added under License is wrong. It's missing a 'r' at the end. Please fix this.

**Comment by srevinsaju** [comment]
Thank you!

**Comment by ghost** [comment]
also in your Firefox-appimage repository, there is a link under [License](https://github.com/srevinsaju/Firefox-Appimage#license) of developer.mozilla.org . That link isn't valid anymore. 

Great work by the way.
