### ISSUE TITLE
Torrible

### ISSUE THREAD

**Issue by Lonniebiz** [srevinsaju/Brave-AppImage#6]
I appreciate you making this available via AppImage.

Question: Are you able to get Tor working with this AppImage? I never can get that part to work:
![torStatus](https://user-images.githubusercontent.com/151919/150440226-faadde3a-fe21-4c97-9ef0-c201dea97110.png)

**Comment by matej118111** [comment]
What about if you try to use bridge?

**Comment by srevinsaju** [comment]
First, nice issue title :sweat_smile: .

I'm curious, are you able to use Tor using any of the linux builds available here: https://github.com/brave/brave-browser/releases ?

**Comment by Lonniebiz** [comment]
The last time I got Tor to work was via a Snap package of Brave on Kubuntu 20.04. But, I've moved away from Snaps and now use AppImages exclusively. I have nothing against flatpaks, but I only use AppImages due to their portability (they don't need an package manager -- I like that).

Before I install these releases you mention, I'd like to know if tor works for you in the AppImage. Can you open a tor privacy tab and navigate to any website? If it works for you then maybe I have some unmet dependency on Debian 11. This is quite possible since I'm only running [Awesome](https://awesomewm.org/), which isn't really a full "desktop environment".

**Comment by srevinsaju** [comment]
Yes, I can confirm Private browser with Tor works on my desktop, with AppImage running on Fedora 35 Silverblue. I do not have `tor` installed on my host.

**Comment by Lonniebiz** [comment]
@srevinsaju Thanks for confirming. I still can't get the tor feature to work for me (even in the latest nightly AppImages). I wish I knew what was blocking this for me and not others. It seems like a great feature.
