### ISSUE TITLE
Latest official stable release not being updated

### ISSUE THREAD

**Issue by Haagen-Dazs** [srevinsaju/Brave-AppImage#8]
According to https://brave-browser-downloads.s3.brave.com/ the latest official release up to now is `1.40.105` and AppImage latest stable is `1.38.71`.

**Comment by Lonniebiz** [comment]
This is where I go to look for updates:
https://github.com/srevinsaju/Brave-AppImage/releases/tag/stable

I wish that page told me which version I'm getting. I never know whether I already have it or not until I download it and look inside Brave.

**Comment by eljamm** [comment]
I've been working on this for the past few days and I fixed the failed updates and also made the release version appear in the continuous page, among other improvements.

I've already submitted a pull request to get this merged, but in the meantime you can check out [my fork](https://github.com/eljamm/Brave-AppImage) if you would like to give it a try or see how it looks.

Also, you can check if a new version is out or not by using the [AppImageUpdate](https://github.com/AppImage/AppImageUpdate) tool which also makes it possible to update an AppImage by only downloading the difference between releases and without re-downloading the whole file.

**Comment by srevinsaju** [comment]
Thank you @eljamm for upstreaming your contributions, apoligies that it took a long time, but its finally on master!.

**Comment by eljamm** [comment]
It's ok, I understand what it's like to be busy 😅. I did learn a lot from this, though, so thanks @srevinsaju for this amazing project 🥳
